### ISSUE TITLE
Unable to fetch profile when characters are missing artifacts

### ISSUE THREAD

**Issue by Peacerekam** [Jelosus2/enkanetwork.js#1]
Fetching profile fails when a character has any of the artifact slots empty
![obraz](https://user-images.githubusercontent.com/26521952/182465656-063d0162-4582-4fe5-8f61-9ba016c36ca1.png)

```js
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at new AffixMap (D:\...\node_modules\enkanetwork.js\dist\structs\AffixMap.js:9:34)
    at new WeaponInfo (D:\...\node_modules\enkanetwork.js\dist\structs\WeaponInfo.js:12:32)
)
    at D:\...\node_modules\enkanetwork.js\dist\structs\EquipList.js:11:88
    at Array.map (<anonymous>)
    at new EquipList (D:\...\node_modules\enkanetwork.js\dist\structs\EquipList.js:11:74)
    at new CharactersInfo (D:\...\node_modules\enkanetwork.js\dist\structs\CharactersInfo.js:28:26)
    at D:\...\node_modules\enkanetwork.js\dist\structs\Data.js:12:87
    at Array.map (<anonymous>)
```
    
as  workaround I added a simple guard clause in `.\enkanetwork.js\dist\structs\AffixMap.js`, dunno how you want to deal with it tho

**Comment by Peacerekam** [comment]
mistake on my part
